### ISSUE TITLE
Detect destination fields data types by entity response shape

### ISSUE THREAD

**Issue by koltyakov** [koltyakov/cq-source-sharepoint#11]
E.g.

```yaml
  lists:
     Shared Documents:
        select:
          - FileRef
          - Author/Title
          - File/Length
        expand:
          - Author
          - File
```

we can check that Author/Title is string and File/Length is int.
