### ISSUE TITLE
Add User Profile Services support

### ISSUE THREAD

**Issue by koltyakov** [koltyakov/cq-source-sharepoint#13]

**Comment by koltyakov** [comment]
A basic version is implemented. Not yet releases, as I need to clean up a few things.

If you need this functionality already, ping here, I'll ship sooner.

**Comment by koltyakov** [comment]
Published with v1.4.0.

User Profiles are fetched via Search API, so the search should be configured in the farm.

Search drived data source can be user only with user associated authentication strategies. E.g. it won't work with `addin` strategy.

```yaml
# sharepoint.yml
# ...
spec:
  # Inclide `profiles` property to fetch user profiles
  # Object structure for extensibility (adding custom properties)
  profiles:
    enabled: true
    # Optional, an alias for the table name
    alias: "profile"
```
