### ISSUE TITLE
How to include file path?

### ISSUE THREAD

**Issue by rajaseg** [koltyakov/cq-source-sharepoint#16]
@koltyakov, Thank you very much for your contribution to the plugin. I am testing the plugin to ingest data into Elasticsearch.
I wanted to include file path. Can you guide me on it?

```
lists:
    Shared Documents:
        select:
            - FileLeafRef
            - FileRef
            - FileDirRef
            - Author/Title
            - File/Length
```
#### Shared Documents File Details (SharePoint)
![image](https://user-images.githubusercontent.com/633479/223383149-76d8e6b7-cb1e-4122-b879-a9d05af0bcb3.png)

#### Elasticsearch Details
![image](https://user-images.githubusercontent.com/633479/223382514-34e5f45e-ce05-43e6-bf7e-1e6075ad629f.png)

**Comment by koltyakov** [comment]
Hi @rajaseg,

Thanks for trying the plugin. It's so important to collect feedback on this early stages.

Technically, `Fileref` is the path to the file, relative to the document library.

Please try this as well:

```yaml
lists:
    Shared Documents:
        select:
            - EncodedAbsUrl # Absolute URL
            - File/ServerRelativeUrl # SharePoint host relative URL 
        expand:
            - File
```
