### ISSUE TITLE
Is it possible to rename the fields?

### ISSUE THREAD

**Issue by rajaseg** [koltyakov/cq-source-sharepoint#17]
@koltyakov, I wanted to rename the fields before saving to destination. Is there any way to achieve?

```
Shared Documents:
        select:
          - FileLeafRef
          - FileRef
          - FileDirRef
          - Author/Title
          - File/Length
          - EncodedAbsUrl
```
I wanted to rename ```EncodedAbsUrl``` to ```url``` and ```FileLeafRef``` to ```File_name```

**Comment by koltyakov** [comment]
Hi @rajaseg,

Currently this is not possible. Fields are mapped automatically based on original name and transformation rules.

I'll check out what will be the most native way for doing this later.

**Comment by rajaseg** [comment]
> Hi @rajaseg,
> 
> Currently this is not possible. Fields are mapped automatically based on original name and transformation rules.
> 
> I'll check out what will be the most native way for doing this later.

@koltyakov, Thank you very much.

**Comment by koltyakov** [comment]
Hey @rajaseg,

Added a feature which makes it possible to alias fields in v1.5.0.

```yaml
Shared Documents:
  select:
    - FileLeafRef -> file_name
    - FileRef
    - FileDirRef
    - Author/Title
    - File/Length
    - EncodedAbsUrl -> url
```
