### ISSUE TITLE
UnauthorizedAccessException where connection worked previously

### ISSUE THREAD

**Issue by jkoppelm** [koltyakov/cq-source-sharepoint#27]
I have a very simple Sharepoint source connection that worked fine up until this morning.  With no changes to the yaml, I am now getting:

`Error: failed to sync v3 source sharepoint: rpc error: code = Internal desc = failed to init plugin: failed to initialize client: failed to connect to SharePoint: unable to request api: 403 Forbidden :: {"error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Attempted to perform an unauthorized operation."}}}`

The same thing happens with 1.8.2 and 2.0.0.

```
kind: source
spec:
  name: "sharepoint"
  registry: "github"
  path: "koltyakov/sharepoint"
  version: "v1.8.2"
  destinations: ["file"]
  tables: ["*"]
  spec:
    auth:
      strategy: "ondemand"
      creds:
        siteUrl: "https://sunpowercorp.sharepoint.com/sites/Engineering"
    lists:
      Lists/COE:
```

I have no problem hitting the list in a browser: 
https://sunpowercorp.sharepoint.com/sites/Engineering/Lists/COE
