### ISSUE TITLE
Add support for user information list 

### ISSUE THREAD

**Issue by koltyakov** [koltyakov/cq-source-sharepoint#6]

**Comment by koltyakov** [comment]
#### User Information List

Quite often you'd need getting User Information List for Author and Editor fields joining. This is a special case, and we have a dedicated configuration for it.

```yaml
# sharepoint.yml
# ...
  spec:
    lists:
      _catalogs/users: # UIL list URI, source of People Picker lookup
        select:
          - Title
          - FirstName
          - LastName
          - JobTitle
          - Department
          - EMail
          - IsSiteAdmin
          - Deleted
        alias: "user"
```
